Adds html pages and content based on wireframe sketches
INF7420/richmond-project pull request #3
Opened 2018-09-26 14:45 UTC by krichmond06

2018-09-28 01:22 UTC, axamei requested changes
In addition to the footer, I recommend adding a `<header>` and `<main>` element with the appropriate elements nested inside those tags. This will create a more meaningful structure for your pages.

2018-09-28 01:22 UTC, axamei commented on contact.html
> +  <title>Document</title>
I recommend changing the title of your pages.

2018-09-28 01:22 UTC, axamei commented on contact.html
> +  <div id="footer">
Instead of the div, I recommend using the `<footer>` element.

2018-09-28 13:14 UTC, krichmond06 commented
Thank you for your suggestions, Axa! I have made the suggested changes and pushed the new commit. Thanks!

2018-09-28 17:24 UTC, axamei requested changes
I recommend you change the title of your pages / the text between the `<title></title>` tags in the head of the document.

2018-09-29 00:54 UTC, krichmond06 commented
Oops, I changed the title on the index page, but forgot to change it on the others. I have changed it now, but am running into an issue with pushing the changes. I keep getting this message when trying to add files to commit: "Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue." I've closed all other processes, so I'm not sure what the issue is?

2018-09-29 01:09 UTC, krichmond06 commented
I believe I deleted the correct file that was causing the issue and have pushed the changes now.

2018-09-29 18:34 UTC, axamei approved these changes

2018-09-29 18:34 UTC, merged